fun main (){
    print("Student Enrollment no:")
    val en= readLine()
    print("Student name:")
    val name= readLine()
    print("Student Branch:")
    val branch= readLine()
    print("Student Class:")
    val c= readLine()
    print("Student Collage Name:")
    val cn= readLine()
    print("Student University Name:")
    val un= readLine()
    print("Student Age:")
    val age= readLine()

    println("/n/n********************/n/n")

    println("Student Data:")
    println("Enrollment:$en")
    println("Name:$name")
    println("Branch:$branch")
    println("Class:$c")
    println("Collage Name:$cn")
    println("University Name:$un")
    println("Age:$age")
}